version: 0.2

phases:
  build:
    commands:
      - make deploy

  deploy:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
      - docker build -t myfastapi . 
      - docker tag myfastapi:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/myfastapi:latest
      - docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/myfastapi:latest
